export const FETCH_PLACES_DATA_START = "FETCH_PLACES_DATA_START";
export const FETCH_PLACES_DATA_SUCCESS = "FETCH_PLACES_DATA_SUCCESS";
export const FETCH_PLACES_DATA_FAIL = "FETCH_PLACES_DATA_FAIL";
